<?php
/**
 * Copyright © Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/* @var \Amazon\Pay\Block\Adminhtml\System\Config\Form\ResetAutoKeyExchange $block */
?>

<div class="reset-auto-key-exchange">
    <button id="reset-auto-key-exchange-button" type="button"><?= /* @noEscape */ __('Reset Registration') ?></button>
    <br />
    <span id="reset-auto-key-exchange-message">
        <?= /* @noEscape */ __('Please wait, resetting internal public/private key pair. Once the page reloads, ' .
        'please re-try automatic configuration.'); ?>
    </span>
</div>
